#ifndef DISPLAYDEFINES_H
#define DISPLAYDEFINES_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define DISPLAY_WIDTH (SCREEN_WIDTH)
#define DISPLAY_HEIGHT (SCREEN_HEIGHT)

#ifndef SCREEN_DEPTH
#define SCREEN_DEPTH 8
#endif

#endif //DISPLAYDEFINES_H
